apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: wp-web
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  selector:
    matchLabels:
      app: wp-web
  template:
    metadata:
      labels:
        app: wp-web
    spec:
      containers:
        - name: web
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Values.dbhost }}
            - name: WORDPRESS_DB_NAME
              value: "wp"
            - name: WORDPRESS_DB_USER
              value: "wp"
            - name: WORDPRESS_DB_PASSWORD
              value: "secretWp"
              
