apiVersion: v1
kind: Service
metadata:
  name: wp-external
  namespace: frontend
spec:
  type: NodePort 
  selector:
    app: wp-web
  ports:
    - protocol: TCP
      nodePort: 30001
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      