apiVersion: v1
kind: Service
metadata:
  name: wp-external
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort 
  selector:
    app: wp-web
  ports:
    - protocol: TCP
      nodePort: {{ .Values.nodeport }}
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      